#!/bin/bash

SRC_PATH="/home/mum-chen/Test-Env"
cd ${SRC_PATH}
FILE_PATH="`pwd`/abbr.note";

edit()
{
	vim ${FILE_PATH}
}

search_head()
{
	grep "^$1" ${FILE_PATH} -i | sort
}

search(){
	grep "$1" ${FILE_PATH} -i | sort
}

usage()
{
	echo "abbr($0) usage"
	echo "   abbr <keyword>"
	echo "   -h help"
	echo "   -a <keyword> content #find all, default param"
	echo "   -s <keyword> content #find with start"
	echo "   -e         #edit abbr"
	echo "   -f         #echo file path"
}


case $1 in
	-e)
		edit
		;;
	-h)
		usage
		;;
	-a)
		search $2
		;;
	-f)
		echo ${FILE_PATH}
		;;
	-s)
		search_head $2
		;;
	*)
		search $1
		;;
esac

