#! /bin/bash

LOCAL_PATH=`pwd`
DEV_TOOLS_PATH='/home/mum-chen/Test-Env'


kclean()
{
	SOURCE_PATH="/home/mum-chen/wrt/MTK_SDK/RT288x_SDK/source"
	cd ${SOURCE_PATH}
	make clean;
}

kmake()
{
	SOURCE_PATH="/home/mum-chen/wrt/MTK_SDK/RT288x_SDK/source"
	cd ${SOURCE_PATH}
	make dep; make V=s && cp images/mum-chen_uImage /var/lib/tftpboot/ && stat /var/lib/tftpboot/mum-chen_uImage
}

download_test()
{
	BIT=${1:-"100k"}
	FILE=${2:-"hello.tar"}

	while true; do
		wget http://192.168.1.1/${FILE} --user=admin --password=admin -O /dev/null --limit-rate=${BIT}
		sleep 1
	done
}


menuconfig()
{
	SOURCE_PATH="/home/mum-chen/wrt/MTK_SDK/RT288x_SDK/source"
	cd ${SOURCE_PATH}
	make menuconfig ;
}

bindir()
{
	P="/var/lib/tftpboot/"
	echo "dir:"
	echo "$P"
	sh -c "cd $P"
}


bintool()
{
	
	# don't have pattern
	if [ -z "$2" ]; then
		oper="-b"
	else
		oper="-bits"
	fi
	
	cd ${DEV_TOOLS_PATH}
	./bintools ${oper} $1 $2
}


gitproxy()
{
	./gitproxy $1
	
}

usage()
{
	echo "$0 usage"
	echo "   make                     # make uImage"
	echo "   menu                     # make menuconfig"
	echo "   bindir                   # go to image dir"
	echo "   down [rate] [file]       # download test"
	echo "   bits hex-num [pattern]   # bintools"
	echo "   gitproxy <on|off|status>"
}



case $1 in
clean)
	# kclean
	;;
make)
	kmake
	;;
down)
	download_test $2 $3
	;;
menu)
	menuconfig
	;;
bits)
	bintool $2 $3
	;;
bindir)
	bindir
	;;
gitproxy)
	gitproxy $2
	;;

*)
	usage
	;;
esac
