" set width
set ts=8
set st=8
set autoindent
set smartindent
set noexpandtab
set softtabstop=8
" set hlsearch

set relativenumber

" common setting
set ruler
set number
set showcmd
set tag=tags;/

" viem setting
syn on se title
set background=dark

set list
" set nolist
set list listchars=tab:»\ ,trail:.,extends:»,precedes:«
" set listchars=tab:\⋮\ ,trail:·,eol:↲,extends:»,precedes:«,nbsp:%

" set marker
set fdm=marker

" else
" filetype plugin indent on
" Bundle 'Valloric/YouCompleteMe'

filetype plugin on
